name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"

      - name: Loom Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/wrapper-validation-action@v2

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: |
            fabric/build/libs/
            forge/build/libs/
            
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Create tag for release
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag autobuild-${{ github.run_number }}
        git push origin autobuild-${{ github.run_number }}

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: Package
        path: forge/build/libs

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: autobuild-${{ github.run_number }}
        name: Auto Release ${{ github.run_number }}
        body: |
          ${{ github.event.head_commit.message }}
          
          ${{ steps.commit_info.outputs.body }}
        draft: false
        prerelease: true
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
